### PR TITLE
fix motion detection for newer firmware

### PR DESCRIPTION
**Pull request by darkxst**
Restore MQTT motion events on firmware ```V5520.2053.0402build20220712```.  Manually set config MQTT_IPCSYS_DB=0 for these devices. This could be set automatically when saving the mqtt config, however I not sure exactly which models/firmware are affected.

Probably resolves issue #69

### CODE REVIEW

**Comment by roleoroleo** [comment]
I think this solution also works on old firmware.
I need a couple of days to test it on my cam but probably we could set MQTT_IPCSYS_DB=1 for all models.

**Comment by darkxst** [comment]
I assume you meant MQTT_IPCSYS_DB=0? If that works on all models, maybe dont really need the config flag. However maybe safer to keep it just in case its needed on others?

**Comment by roleoroleo** [comment]
> I assume you meant MQTT_IPCSYS_DB=0?

Yes.

> If that works on all models, maybe dont really need the config flag. However maybe safer to keep it just in case its needed on others?

I think it's best to leave it.

I will test in the weekend.

**Comment by roleoroleo** [comment]
I tested the new db with the old cam.
It works but the row arrives 30-40 seconds after the event while in ipcsys.db it arrives immediately.
I think it would be better to add the option to the interface or try to detect automatically if ipcsys.db exists.

**Comment by darkxst** [comment]
@roleoroleo ipcsys.db always exists, just that ```t_alarm_log``` table is always empty on these new cameras/firmwares.

I not sure on the behaviour of the older cams, however even the eWeLink notifications seem to have similar delay for the motion events (on my camera). Its as if they dont trigger until the video is finished recording.

Where does this point on your camera?
```sqlite3 /mnt/mtd/db/ipcsys.db 'select * from t_rec_dbfile'```
do its show the ipcsys.db or the db on the sd card?

**Comment by darkxst** [comment]
or the other option would be to set the option based on firmware version perhaps? but happy to add it into the webUI as an option.

**Comment by roleoroleo** [comment]
> Where does this point on your camera?
```
[root@GK]# sqlite3 /mnt/mtd/db/ipcsys.db "select * from t_rec_dbfile;"
2022-03-01 14:48:48|/mnt/mmc/AVRecordFile.db
```

Probably a manual option into the web gui is better.

**Comment by darkxst** [comment]
OK, will add that shortly. 

Have you dont any work to investigate the ipc of the AlarmServer app? I do wonder if there is a way to get instant notification of events on these firmware.

**Comment by roleoroleo** [comment]
> Have you done any work to investigate the ipc of the AlarmServer app? I do wonder if there is a way to get instant notification of events on these firmware.

No, I didn't work on it at the moment.

**Comment by darkxst** [comment]
I have added manual option to webui (and reverted to default setting of 1)

**Comment by roleoroleo** [comment]
Thank you again for your code.

**Pull request merged**
