### PR TITLE
Add vscode .devcontainer build

### PR DESCRIPTION
**Pull request by darkxst**
I had trouble building under recent Ubuntu 22.04. Including with the current Docker file in this repo.

This is largely copied from the one in your other yi-hack repo. Just tweaked a little for this project.

### CODE REVIEW

**Comment by roleoroleo** [comment]
compile.sh works properly.
pack_fw.all.sh fails when it try to copy
/home/user/x-tools/arm-sonoff-linux-uclibcgnueabi/arm-sonoff-linux-uclibcgnueabi/sysroot/lib/libcrypt.so.0
Because the toochain path is different.
Only for model GK-200MP2-B.
Does it work for you?

**Comment by roleoroleo** [comment]
compile.sh works properly.
pack_fw.all.sh fails when it tries to copy
/home/user/x-tools/arm-sonoff-linux-uclibcgnueabi/arm-sonoff-linux-uclibcgnueabi/sysroot/lib/libcrypt.so.0
Because the toochain path is different.
Only for model GK-200MP2-B.
Does it work for you?

**Comment by darkxst** [comment]
yes, however I was passing the PATH into the sudo shell like below:

``` sudo --preserve-env=PATH ./scripts/pack_fw_all.sh```

**Comment by darkxst** [comment]
We can drop the requirement to run pack_fw.all.sh as root. This avoids the PATH issues when running pack_fw as root. It should also fix the github workflow build of GK-200MP2-B image I expect.

**Comment by darkxst** [comment]
The uploaded github artifacts are labeled .tar.gz but actually download as zip files. Thats all a bit weird, last commit bundles them up into a single zip.

**Comment by roleoroleo** [comment]
Thank you for the pr.

> The uploaded github artifacts are labeled .tar.gz but actually download as zip files. Thats all a bit weird, last commit bundles them up into a single zip.

I don't understand.

**Comment by darkxst** [comment]
> > The uploaded github artifacts are labeled .tar.gz but actually download as zip files. Thats all a bit weird, last commit bundles them up into a single zip.
> 
> I don't understand.

The downloaded artifact file was a zip file called for example ```GK-200MP2B.tar.gz.zip``` that contained a copy of the tar file ```GK-200MP2B_0.1.3.tgz```

**Pull request merged**
