### PR TITLE
A few more minor fixes

### PR DESCRIPTION
**Pull request by darkxst**
- Bind mount /var/log to sdcard (includes blank wtmp file to allow busybox to track logins)
- Add an option to enable busybox syslogd for some logging
- Fixup /etc/profile so we get the default PATH set by Dropbear, and add sonoff-hack LD_LIBRARY_PATH (mostly avoiding the need to source env.sh on login session)
- Disable telnet by default, it really should not be used.
- Limit the thumbnailer to only scan todays event folder. This was taking a really long time to just scan and check files that have already been processed. With a couple of weeks of event data it was taking over 30mins for thumbs.sh to complete. As a resullt causing the camera to boot loop due to OOM errors the kernel was unhappy with.

### CODE REVIEW

**Comment by roleoroleo** [comment]
This mount command:
`mount --bind /var/sdcard/log /var/log`
refers to a path where sd card is mounted temporarily.
The final path is /mnt/mmc

Are you sure it's working?

**Comment by darkxst** [comment]
Yes it is working.

/mnt/mmc is not avilable that early in boot. However the bind mount remains in place after boot.

```/dev/mmcblk0p1 on /var/log type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=cp437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)```

**Comment by roleoroleo** [comment]
About /etc/profile, why didn't you put
```
/mnt/mmc/sonoff-hack/bin
/mnt/mmc/sonoff-hack/sbin
/mnt/mmc/sonoff-hack/usr/bin
/mnt/mmc/sonoff-hack/usr/sbin
```
in the PATH as well?

**Comment by darkxst** [comment]
PATH is set in Dropbear per below. What is in /etc/profile is really just a fail-safe in case something goes wrong and no PATH is set. It wont be set there normally apart from maybe in a telnet login?


```#define DEFAULT_ROOT_PATH "/usr/bin:/usr/sbin:/bin:/sbin:/gm/bin:/gm/tools:/mnt/mmc/sonoff-hack/bin:/mnt/mmc/sonoff-hack/sbin:/mnt/mmc/sonoff-hack/usr/bin:/mnt/mmc/sonoff-hack/usr/sbin"```

**Comment by darkxst** [comment]
@roleoroleo I have updated the fallback PATH in /etc/profile to match the non-root default PATH from Dropbear. All root logins via ssh will get the proper PATH already via Dropbear, thus ignoring what is in /etc/profile for PATH setting anyway.

**Comment by roleoroleo** [comment]
Thanks.

**Pull request merged**
